pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }


    
  
    stage('You') {
      steps {
        script {
          sh 'echo "You  Stage"'
        }
      }
    }
    
  }
}