pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }


    
  
    stage('You') {
      steps {
        script {
          sh 'echo "You  Stage"'
        }
      }
    }
    

    stage('seyi') {
      steps {
        script {
          sh 'echo "seyi Stage"'
        }
      }
    }

    stage('Dare') {
      steps {
        script {
          sh 'echo "Dare Stage"'
        }
      }
    }
  }
}