---
- name: Deploying the PHP Applicaion to Dev Enviroment
  become: true
  hosts: nginx

  tasks:
    - name: install nginx on the webserver
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: ensure nginx is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started 
        enabled: yes